name: leaf republic
favicon: null
layout_spectrum: 0.2789483319502324
typography_spectrum: 0.43535
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#009800'
    - '#88745d'
    - '#b7edd3'
    - '#49bb57'
  brandStrength: 0.5886219441890717
  lightness: 0.7608425409998745
  saturation: 0.9942630212754011
  rhythmicContrast: 0.765702337725088
purpose: []
